import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/providers/ThemeProvider/theme-provider";
import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter as FontSa } from "next/font/google";
import Footer from "@/components/footer/footer";
import { Header } from "@/components/pages/home/header/header";

const inter = FontSa({ subsets: ["latin"] });

const fontSa = FontSa({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={ cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSa.variable
      ) }>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem 
        >
          <Header />
          { children }
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
